<?php
include '../config/db_connect.php';

$ad_no = $_GET['ad_no'] ?? '';

if ($ad_no) {
    $stmt = $conn->prepare("SELECT * FROM users WHERE admission_no = ?");
    $stmt->bind_param("s", $ad_no);
    $stmt->execute();
    $student = $stmt->get_result()->fetch_assoc();
}

if (!$student) {
    die("<h1 style='text-align:center; margin-top:50px; font-family:sans-serif;'>INVALID_ID: STUDENT_NOT_FOUND</h1>");
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PCE | VERIFY_IDENTITY</title>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@800&family=JetBrains+Mono:wght@700&display=swap" rel="stylesheet">
    <style>
        body { background: #f0f0f0; font-family: 'Space Grotesk', sans-serif; display: flex; justify-content: center; padding: 20px; }
        .id-card {
            background: white; border: 6px solid black; width: 100%; max-width: 400px;
            padding: 30px; box-shadow: 20px 20px 0px black; text-align: center;
        }
        .profile-img {
            width: 150px; height: 150px; border: 5px solid black; 
            background: #eee; margin-bottom: 20px; object-fit: cover;
        }
        .tag { background: black; color: white; padding: 5px 10px; font-family: 'JetBrains Mono'; font-size: 0.8rem; margin-bottom: 10px; display: inline-block; }
        .data-label { font-family: 'JetBrains Mono'; font-size: 0.7rem; color: #666; margin-top: 15px; }
        .status-valid { color: #00ff00; background: black; padding: 5px; font-size: 1.2rem; margin-top: 20px; border: 3px solid #00ff00; }
    </style>
</head>
<body>
    <div class="id-card">
        <div class="tag">OFFICIAL_VERIFICATION</div>
        
        <?php 
        $img_path = !empty($student['profile_pic']) ? "uploads/profile/" . $student['profile_pic'] : "img/default_avatar.png";
        ?>
        <img src="<?php echo $img_path; ?>" class="profile-img" alt="Student Photo">

        <h1 style="text-transform: uppercase; font-size: 2rem; margin: 0;"><?php echo $student['full_name']; ?></h1>
        
        <p class="data-label">ADMISSION_ID</p>
        <p style="margin: 0; font-weight: 900;"><?php echo $student['admission_no']; ?></p>
        
        <p class="data-label">ROLL_NUMBER</p>
        <p style="margin: 0; font-weight: 900;"><?php echo $student['roll_no']; ?></p>
        
        <div class="status-valid">SYSTEM_STATUS: ACTIVE</div>
        
        <p style="font-size: 0.6rem; margin-top: 30px; font-family: 'JetBrains Mono';">Generated by PCE_CMS Terminal</p>
    </div>
</body>
</html>
